Repository wimpysworld/deb-get, pull requests merged in 2022-10, with the labels that each got.

#550 Print error messages to stderr
  deb-get
Labels: enhancement, hacktoberfest-accepted

#553 Make deb-get executable in test workflow
  .github/workflows/tests.yml
Labels: bug, hacktoberfest-accepted

#544 Fix logic error in validate_deb
  deb-get
Labels: bug, hacktoberfest-accepted

#560 docs: add <list of packages> note to relevant commands
  README.md
Labels: documentation, hacktoberfest-accepted

#479 Add Quarto
  README.md
  deb-get
Labels: new package, hacktoberfest-accepted

#566 added new packages to list in man page
  docs/deb-get.1
  docs/deb-get.1.md
Labels: documentation, hacktoberfest-accepted

#575 dev: added quickobs
  deb-get
Labels: new package, hacktoberfest-accepted

#588 Filter for HOST_ARCH
  deb-get
Labels: bug, hacktoberfest-accepted

#581 One or two too many eligible projects
  HACKTOBERFEST-2022.md
Labels: documentation, hacktoberfest-accepted

#582 Make the list a tasklist
  HACKTOBERFEST-2022.md
Labels: documentation, hacktoberfest-accepted

#583 Moved lutris to github
  deb-get
Labels: enhancement, hacktoberfest-accepted

#584 Added Virtualbox 7.0
  deb-get
Labels: enhancement, hacktoberfest-accepted

#598 align virtualbox APT_LIST_NAMEs :bug:
  deb-get
Labels: enhancement, hacktoberfest-accepted

#600 Update HACKTOBERFEST-2022.md
  HACKTOBERFEST-2022.md
Labels: documentation, hacktoberfest-accepted

#607 Check PR box for Azure Data Studio
  HACKTOBERFEST-2022.md
Labels: documentation, hacktoberfest-accepted
